---
title: "Part 1 3 Variables"
output: pdf_document
---


This is just for the sake of completeness. 
```{r}
library(sp)
library(spmodel)
library(sf) 
library(spdep)
library(tmap)
library(corrplot)
library(readr)
library(tidyverse)
library(tinytex)
library(ggcorrplot)
library(knitr)
library(kableExtra)

## Load in the demographic data and county data for North Carolina
ncdata=read.csv("NCcounty2024data.csv",header=T)
load("nc_counties.Rdata")

## Plot the counties
plot(nc_counties)
## Names of the counties
nc_counties[[7]]
## Obtain neighborhoods given the polygons
nc_neigh=poly2nb(nc_counties)

```

```{r}
# Convert to sf object before merge
nc_counties_sf <- st_as_sf(nc_counties)

# Make sure the name matches
nc_counties_sf$County <- nc_counties_sf$NAME_2

# Now merge
nc_full <- left_join(nc_counties_sf, ncdata, by = "County")

#Neighborhoods for our analyses

# Define spatial neighbors using Queen's Contiguity
nc_nb <- poly2nb(nc_counties_sf, queen = TRUE)


# Convert to a spatial weights list object
nc_listw <- nb2listw(nc_nb, style = "W")  

```


For Food Insecurity: 

```{r}
# Moran's I Test (Global Spatial Autocorrelation)
moran_test_Food <- moran.test(nc_full$Food.Insecurity.2022, nc_listw)

# Geary's C Test (Local Spatial Autocorrelation)
geary_test_Food <- geary.test(nc_full$Food.Insecurity.2022, nc_listw)

# Print results
print(moran_test_Food)
print(geary_test_Food)
```
```{r}
# Moran's I Test (Global Spatial Autocorrelation)
moran_test_Overdose <- moran.test(nc_full$Overdose.Deaths.Per.100.000, nc_listw)

# Geary's C Test (Local Spatial Autocorrelation)
geary_test_Overdose <- geary.test(nc_full$Overdose.Deaths.Per.100.000, nc_listw)

# Print results
print(moran_test_Overdose)
print(geary_test_Overdose)
```

```{r}
# Moran's I Test (Global Spatial Autocorrelation)
moran_test_Poverty <- moran.test(nc_full$Percent.Children.in.Poverty, nc_listw)

# Geary's C Test (Local Spatial Autocorrelation)
geary_test_Poverty <- geary.test(nc_full$Percent.Children.in.Poverty, nc_listw)

# Print results
print(moran_test_Poverty)
print(geary_test_Poverty)
```

```{r}
moran_test_Uninsured <- moran.test(nc_full$Uninsured.Residents.2020, nc_listw)

# Geary's C Test (Local Spatial Autocorrelation)
geary_test_Uninsured <- geary.test(nc_full$Uninsured.Residents.2020, nc_listw)

# Print results
print(moran_test_Uninsured)
print(geary_test_Uninsured)
```

```{r results='asis', echo=FALSE, message=FALSE}
# Create a data frame of the results
results <- data.frame(
  Variable = c("Population", "Percent.Children.in.Poverty", 
               "Food.Insecurity.2022", "Food.Insecurity.2022"),
  Test = c("Moran's I", "Geary's C", "Moran's I", "Geary's C"),
  Statistic = c(0.4170, 0.5751, 0.3780, 0.6500),
  Expectation = c(-0.0101, 1.0000, -0.0101, 1.0000),
  Variance = c(0.00428, 0.00457, 0.00423, 0.00484),
  `Standard Deviate` = c(6.5275, 6.2864, 5.9675, 5.0315),
  `P-value` = c(3.343e-11, 1.625e-10, 1.205e-09, 2.433e-07)
)

# Print table
kable(results, caption = "Spatial Autocorrelation Test Results for Selected Indicators", digits = 4)

```

- Population Change 
_ Food Insecurity 
_ Opportunity Youth 


```{r}
# Moran's I Test (Global Spatial Autocorrelation)
moran_test_Food <- moran.test(nc_full$Food.Insecurity.2022, nc_listw)

# Geary's C Test (Local Spatial Autocorrelation)
geary_test_Food <- geary.test(nc_full$Food.Insecurity.2022, nc_listw)

# Print results
print(moran_test_Food)
print(geary_test_Food)



# Moran's I Test (Global Spatial Autocorrelation)
moran_test_Opportunity <- moran.test(nc_full$Opportunity.Youth.2022, nc_listw)

# Geary's C Test (Local Spatial Autocorrelation)
geary_test_Opportunity <- geary.test(nc_full$Opportunity.Youth.2022, nc_listw)

# Print results
print(moran_test_Opportunity)
print(geary_test_Opportunity)

# Moran's I Test (Global Spatial Autocorrelation)
moran_test_Population_Change <- moran.test(nc_full$Population.Change.Since.2014, nc_listw)

# Geary's C Test (Local Spatial Autocorrelation)
geary_test_Population_Change <- geary.test(nc_full$Population.Change.Since.2014, nc_listw)

# Print results
print(moran_test_Population_Change)
print(geary_test_Population_Change)
```



```{r}
# Create a data frame with all Moran's I and Geary's C results
results <- data.frame(
  Variable = c(
    "Food.Insecurity.2022", "Food.Insecurity.2022",
    "Opportunity.Youth.2022", "Opportunity.Youth.2022",
    "Population.Change.Since.2014", "Population.Change.Since.2014"
  ),
  Test = c(
    "Moran's I", "Geary's C",
    "Moran's I", "Geary's C",
    "Moran's I", "Geary's C"
  ),
  Statistic = c(
    0.3780, 0.6500,
    0.4246, 0.5560,
    0.2303, 0.7912
  ),
  Expectation = c(
    -0.0101, 1.0000,
    -0.0101, 1.0000,
    -0.0101, 1.0000
  ),
  Variance = c(
    0.00423, 0.00484,
    0.00426, 0.00467,
    0.00305, 0.01099
  ),
  `Standard Deviate` = c(
    5.9675, 5.0315,
    6.6589, 6.4946,
    4.3538, 1.9915
  ),
  `P-value` = c(
    1.205e-09, 2.433e-07,
    1.379e-11, 4.164e-11,
    6.691e-06, 2.322e-02
  )
)

# Print table
kable(results, caption = "Spatial Autocorrelation Test Results (Moran's I and Geary's C)", digits = 4)
```

```

